version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - restore_cache:
          keys:
          - spotify-authentication-

      - run:
          name: run job
          command: |
            . venv/bin/activate
            echo $AUTH_CODE | python3 ./src/main.py
      
      - save_cache:
          paths:
            - ./spotify_authentication.json
          key: spotify-authentication-{{ checksum "spotify_authentication.json" }}

workflows:
  version: 2
  run:
    triggers:
      - schedule:
          cron: "0 9-17 * * *"
          filters:
             branches:
               only:
                 - master
    jobs:
      - build